jdbcSettings:
  url: "jdbc:mysql://mysql.cc.puv.fi:3306/e1800927_northwind"
  username: "e1800927"
  password: "ztUb9wefuyDm"
  driverClassName: "com.mysql.jdbc.Driver"

packageName: "fi.vamk.e1800927.northwind"